### ISSUE TITLE
Add-Font or Remove-Font scripts calling directly.

### ISSUE THREAD

**Issue by tignear** [tignear/choco-cica#1]
I wrote the script referring to https://chocolatey.org/packages/fonts-ricty-diminished

I received the following comment.
> Pauby (reviewer) on 16 Jul 2019 08:25:28 +00:00:
> 
> Hi,
> 
> My apologies as I should have brought this up last time!
> 
> In your chocolateyInstall.ps1 and chocolateyUninstall.ps1 you are calling powershell.exe -f with the Add-Font or Remove-Font scripts. Is there a reason you are doing this over just calling the scripts directly?
> 
> You are effectively launching PowerShell inside PowerShell which doesn't make a lot of sense 
but there could be a reason for it?

I thought it was the best, so I decided to fix it.
Rewrote chocolateyUninstall.ps1 as follows.
```powershell
$ErrorActionPreference = 'Continue';
$toolsDir   = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"
 
$fonts =  Join-Path $toolsDir "fonts"
$removeFontScript=Join-Path $toolsDir "Remove-Font.ps1";
Get-ChildItem $fonts |ForEach-Object {&($removeFontScript) ([System.IO.Path]::GetFileName($_))}

```

However, this does not work well with the following output.
```
Chocolatey v0.10.15
Uninstalling the following packages:
cica

cica v5.0.1
Font: Cica-Bold (TrueType)
An error occured removing $'Cica-Bold.ttf'

You cannot call a method on a null-valued expression.
Font: Cica-BoldItalic (TrueType)
Font 'Cica-BoldItalic.ttf' removed successfully

Font: Cica-Regular (TrueType)
Font 'Cica-Regular.ttf' removed successfully

Font: Cica-RegularItalic (TrueType)
Font 'Cica-RegularItalic.ttf' removed successfully

'C:\Windows\Fonts\COPYRIGHT.txt' not found

'C:\Windows\Fonts\LICENSE.txt' not found

 Skipping auto uninstaller - No registry snapshot.
 cica has been successfully uninstalled.

Chocolatey uninstalled 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by pauby** [comment]
Have a look at how [Fira Code Font Package](https://chocolatey.org/packages/FiraCode-ttf/1.207) does it.

**Comment by tignear** [comment]
@pauby 
Thank you.
It went well!
